### ISSUE TITLE
Ого маєш класну курсову!

### ISSUE THREAD

**Issue by d1vory** [starboss1/course_work#1]
Кремезний код!
Неймовірно милі фреймворки!
Приголомшливий бекенд!

**Comment by starboss1** [comment]
> Кремезний код!
> Неймовірно милі фреймворки!
> Приголомшливий бекенд!

Єй, чоловіче, я вважаю ти помилився дверима. Клуб любителів зміюк двома поверхами нижче.

**Comment by d1vory** [comment]
Пітухон це стіль жизні

**Comment by d1vory** [comment]
Жаваскріптізєрам не поняти

**Comment by d1vory** [comment]
Тепер я буду слідкувати за твоїми комітами♿♿♿😂😂😂😂

**Comment by starboss1** [comment]
> Пітухон це стіль жизні

Як кажуть, якщо змієносець мовчить, то краще його не перебивати
